version: "3.9"

services:
  web:
    build:
      target: dev
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/html:rw,default
    environment:
      PUID: 1000
      PGID: 1000
      SSL_MODE: mixed
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
